version: "3.9"
services:
  minio:
    image: bitnami/minio:2021
    ports:
      - '29000:9000'
      - '29001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
